### ISSUE TITLE
housekeeping

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-xpathjs#78]
* [x] ~~use jsbeautifier config + tests, and exclude only engine.js and parser.peg~~ => #80
* [x] use eslint and use separate passing config for engine.js perhaps
* [x] ~~convert tests to es6~~ => #80
* [ ] run tests without having to create a bundle file, using karma-browserify
* [x] ~~convert tests so each looped test has its own `it()` statement~~ => #80
* [ ] complete and consistent JSDoc for custom functions
